/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as OnBoardingRouteImport } from './routes/on-boarding'
import { Route as ForDriversRouteImport } from './routes/for-drivers'
import { Route as ForCarriersRouteImport } from './routes/for-carriers'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DriverIndexRouteImport } from './routes/driver.index'
import { Route as CompanyIndexRouteImport } from './routes/company.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as DriverProfileRouteImport } from './routes/driver.profile'
import { Route as DriverMapRouteImport } from './routes/driver.map'
import { Route as DriverAuthRouteImport } from './routes/driver.auth'
import { Route as CompanyMapRouteImport } from './routes/company.map'
import { Route as CompanyJobsRouteImport } from './routes/company.jobs'
import { Route as CompanyBenchmarksRouteImport } from './routes/company.benchmarks'
import { Route as CompanyAuthRouteImport } from './routes/company.auth'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppNoctiRouteImport } from './routes/app.nocti'
import { Route as AppMapRouteImport } from './routes/app.map'
import { Route as DriverCarriersIndexRouteImport } from './routes/driver.carriers.index'
import { Route as CompanyDriversIndexRouteImport } from './routes/company.drivers.index'
import { Route as AppCompaniesIndexRouteImport } from './routes/app.companies.index'
import { Route as DriverCarriersIdRouteImport } from './routes/driver.carriers.$id'
import { Route as CompanyDriversIdRouteImport } from './routes/company.drivers.$id'
import { Route as AppCompaniesIdRouteImport } from './routes/app.companies.$id'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const OnBoardingRoute = OnBoardingRouteImport.update({
  id: '/on-boarding',
  path: '/on-boarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ForDriversRoute = ForDriversRouteImport.update({
  id: '/for-drivers',
  path: '/for-drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForCarriersRoute = ForCarriersRouteImport.update({
  id: '/for-carriers',
  path: '/for-carriers',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/driver/',
  path: '/driver/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyIndexRoute = CompanyIndexRouteImport.update({
  id: '/company/',
  path: '/company/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const DriverProfileRoute = DriverProfileRouteImport.update({
  id: '/driver/profile',
  path: '/driver/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverMapRoute = DriverMapRouteImport.update({
  id: '/driver/map',
  path: '/driver/map',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverAuthRoute = DriverAuthRouteImport.update({
  id: '/driver/auth',
  path: '/driver/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyMapRoute = CompanyMapRouteImport.update({
  id: '/company/map',
  path: '/company/map',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyJobsRoute = CompanyJobsRouteImport.update({
  id: '/company/jobs',
  path: '/company/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyBenchmarksRoute = CompanyBenchmarksRouteImport.update({
  id: '/company/benchmarks',
  path: '/company/benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyAuthRoute = CompanyAuthRouteImport.update({
  id: '/company/auth',
  path: '/company/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNoctiRoute = AppNoctiRouteImport.update({
  id: '/nocti',
  path: '/nocti',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const DriverCarriersIndexRoute = DriverCarriersIndexRouteImport.update({
  id: '/driver/carriers/',
  path: '/driver/carriers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyDriversIndexRoute = CompanyDriversIndexRouteImport.update({
  id: '/company/drivers/',
  path: '/company/drivers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCompaniesIndexRoute = AppCompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => AppRoute,
} as any)
const DriverCarriersIdRoute = DriverCarriersIdRouteImport.update({
  id: '/driver/carriers/$id',
  path: '/driver/carriers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyDriversIdRoute = CompanyDriversIdRouteImport.update({
  id: '/company/drivers/$id',
  path: '/company/drivers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCompaniesIdRoute = AppCompaniesIdRouteImport.update({
  id: '/companies/$id',
  path: '/companies/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/for-carriers': typeof ForCarriersRoute
  '/for-drivers': typeof ForDriversRoute
  '/on-boarding': typeof OnBoardingRoute
  '/verify': typeof VerifyRoute
  '/app/map': typeof AppMapRoute
  '/app/nocti': typeof AppNoctiRoute
  '/app/profile': typeof AppProfileRoute
  '/company/auth': typeof CompanyAuthRoute
  '/company/benchmarks': typeof CompanyBenchmarksRoute
  '/company/jobs': typeof CompanyJobsRoute
  '/company/map': typeof CompanyMapRoute
  '/driver/auth': typeof DriverAuthRoute
  '/driver/map': typeof DriverMapRoute
  '/driver/profile': typeof DriverProfileRoute
  '/app/': typeof AppIndexRoute
  '/company/': typeof CompanyIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/app/companies/$id': typeof AppCompaniesIdRoute
  '/company/drivers/$id': typeof CompanyDriversIdRoute
  '/driver/carriers/$id': typeof DriverCarriersIdRoute
  '/app/companies/': typeof AppCompaniesIndexRoute
  '/company/drivers/': typeof CompanyDriversIndexRoute
  '/driver/carriers/': typeof DriverCarriersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/for-carriers': typeof ForCarriersRoute
  '/for-drivers': typeof ForDriversRoute
  '/on-boarding': typeof OnBoardingRoute
  '/verify': typeof VerifyRoute
  '/app/map': typeof AppMapRoute
  '/app/nocti': typeof AppNoctiRoute
  '/app/profile': typeof AppProfileRoute
  '/company/auth': typeof CompanyAuthRoute
  '/company/benchmarks': typeof CompanyBenchmarksRoute
  '/company/jobs': typeof CompanyJobsRoute
  '/company/map': typeof CompanyMapRoute
  '/driver/auth': typeof DriverAuthRoute
  '/driver/map': typeof DriverMapRoute
  '/driver/profile': typeof DriverProfileRoute
  '/app': typeof AppIndexRoute
  '/company': typeof CompanyIndexRoute
  '/driver': typeof DriverIndexRoute
  '/app/companies/$id': typeof AppCompaniesIdRoute
  '/company/drivers/$id': typeof CompanyDriversIdRoute
  '/driver/carriers/$id': typeof DriverCarriersIdRoute
  '/app/companies': typeof AppCompaniesIndexRoute
  '/company/drivers': typeof CompanyDriversIndexRoute
  '/driver/carriers': typeof DriverCarriersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/for-carriers': typeof ForCarriersRoute
  '/for-drivers': typeof ForDriversRoute
  '/on-boarding': typeof OnBoardingRoute
  '/verify': typeof VerifyRoute
  '/app/map': typeof AppMapRoute
  '/app/nocti': typeof AppNoctiRoute
  '/app/profile': typeof AppProfileRoute
  '/company/auth': typeof CompanyAuthRoute
  '/company/benchmarks': typeof CompanyBenchmarksRoute
  '/company/jobs': typeof CompanyJobsRoute
  '/company/map': typeof CompanyMapRoute
  '/driver/auth': typeof DriverAuthRoute
  '/driver/map': typeof DriverMapRoute
  '/driver/profile': typeof DriverProfileRoute
  '/app/': typeof AppIndexRoute
  '/company/': typeof CompanyIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/app/companies/$id': typeof AppCompaniesIdRoute
  '/company/drivers/$id': typeof CompanyDriversIdRoute
  '/driver/carriers/$id': typeof DriverCarriersIdRoute
  '/app/companies/': typeof AppCompaniesIndexRoute
  '/company/drivers/': typeof CompanyDriversIndexRoute
  '/driver/carriers/': typeof DriverCarriersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/for-carriers'
    | '/for-drivers'
    | '/on-boarding'
    | '/verify'
    | '/app/map'
    | '/app/nocti'
    | '/app/profile'
    | '/company/auth'
    | '/company/benchmarks'
    | '/company/jobs'
    | '/company/map'
    | '/driver/auth'
    | '/driver/map'
    | '/driver/profile'
    | '/app/'
    | '/company/'
    | '/driver/'
    | '/app/companies/$id'
    | '/company/drivers/$id'
    | '/driver/carriers/$id'
    | '/app/companies/'
    | '/company/drivers/'
    | '/driver/carriers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/for-carriers'
    | '/for-drivers'
    | '/on-boarding'
    | '/verify'
    | '/app/map'
    | '/app/nocti'
    | '/app/profile'
    | '/company/auth'
    | '/company/benchmarks'
    | '/company/jobs'
    | '/company/map'
    | '/driver/auth'
    | '/driver/map'
    | '/driver/profile'
    | '/app'
    | '/company'
    | '/driver'
    | '/app/companies/$id'
    | '/company/drivers/$id'
    | '/driver/carriers/$id'
    | '/app/companies'
    | '/company/drivers'
    | '/driver/carriers'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/for-carriers'
    | '/for-drivers'
    | '/on-boarding'
    | '/verify'
    | '/app/map'
    | '/app/nocti'
    | '/app/profile'
    | '/company/auth'
    | '/company/benchmarks'
    | '/company/jobs'
    | '/company/map'
    | '/driver/auth'
    | '/driver/map'
    | '/driver/profile'
    | '/app/'
    | '/company/'
    | '/driver/'
    | '/app/companies/$id'
    | '/company/drivers/$id'
    | '/driver/carriers/$id'
    | '/app/companies/'
    | '/company/drivers/'
    | '/driver/carriers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForCarriersRoute: typeof ForCarriersRoute
  ForDriversRoute: typeof ForDriversRoute
  OnBoardingRoute: typeof OnBoardingRoute
  VerifyRoute: typeof VerifyRoute
  CompanyAuthRoute: typeof CompanyAuthRoute
  CompanyBenchmarksRoute: typeof CompanyBenchmarksRoute
  CompanyJobsRoute: typeof CompanyJobsRoute
  CompanyMapRoute: typeof CompanyMapRoute
  DriverAuthRoute: typeof DriverAuthRoute
  DriverMapRoute: typeof DriverMapRoute
  DriverProfileRoute: typeof DriverProfileRoute
  CompanyIndexRoute: typeof CompanyIndexRoute
  DriverIndexRoute: typeof DriverIndexRoute
  CompanyDriversIdRoute: typeof CompanyDriversIdRoute
  DriverCarriersIdRoute: typeof DriverCarriersIdRoute
  CompanyDriversIndexRoute: typeof CompanyDriversIndexRoute
  DriverCarriersIndexRoute: typeof DriverCarriersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/on-boarding': {
      id: '/on-boarding'
      path: '/on-boarding'
      fullPath: '/on-boarding'
      preLoaderRoute: typeof OnBoardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-drivers': {
      id: '/for-drivers'
      path: '/for-drivers'
      fullPath: '/for-drivers'
      preLoaderRoute: typeof ForDriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-carriers': {
      id: '/for-carriers'
      path: '/for-carriers'
      fullPath: '/for-carriers'
      preLoaderRoute: typeof ForCarriersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/': {
      id: '/driver/'
      path: '/driver'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/': {
      id: '/company/'
      path: '/company'
      fullPath: '/company/'
      preLoaderRoute: typeof CompanyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/driver/profile': {
      id: '/driver/profile'
      path: '/driver/profile'
      fullPath: '/driver/profile'
      preLoaderRoute: typeof DriverProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/map': {
      id: '/driver/map'
      path: '/driver/map'
      fullPath: '/driver/map'
      preLoaderRoute: typeof DriverMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/auth': {
      id: '/driver/auth'
      path: '/driver/auth'
      fullPath: '/driver/auth'
      preLoaderRoute: typeof DriverAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/map': {
      id: '/company/map'
      path: '/company/map'
      fullPath: '/company/map'
      preLoaderRoute: typeof CompanyMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/jobs': {
      id: '/company/jobs'
      path: '/company/jobs'
      fullPath: '/company/jobs'
      preLoaderRoute: typeof CompanyJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/benchmarks': {
      id: '/company/benchmarks'
      path: '/company/benchmarks'
      fullPath: '/company/benchmarks'
      preLoaderRoute: typeof CompanyBenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/auth': {
      id: '/company/auth'
      path: '/company/auth'
      fullPath: '/company/auth'
      preLoaderRoute: typeof CompanyAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nocti': {
      id: '/app/nocti'
      path: '/nocti'
      fullPath: '/app/nocti'
      preLoaderRoute: typeof AppNoctiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/map': {
      id: '/app/map'
      path: '/map'
      fullPath: '/app/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/driver/carriers/': {
      id: '/driver/carriers/'
      path: '/driver/carriers'
      fullPath: '/driver/carriers/'
      preLoaderRoute: typeof DriverCarriersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/drivers/': {
      id: '/company/drivers/'
      path: '/company/drivers'
      fullPath: '/company/drivers/'
      preLoaderRoute: typeof CompanyDriversIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/companies/': {
      id: '/app/companies/'
      path: '/companies'
      fullPath: '/app/companies/'
      preLoaderRoute: typeof AppCompaniesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/driver/carriers/$id': {
      id: '/driver/carriers/$id'
      path: '/driver/carriers/$id'
      fullPath: '/driver/carriers/$id'
      preLoaderRoute: typeof DriverCarriersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/drivers/$id': {
      id: '/company/drivers/$id'
      path: '/company/drivers/$id'
      fullPath: '/company/drivers/$id'
      preLoaderRoute: typeof CompanyDriversIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/companies/$id': {
      id: '/app/companies/$id'
      path: '/companies/$id'
      fullPath: '/app/companies/$id'
      preLoaderRoute: typeof AppCompaniesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppMapRoute: typeof AppMapRoute
  AppNoctiRoute: typeof AppNoctiRoute
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCompaniesIdRoute: typeof AppCompaniesIdRoute
  AppCompaniesIndexRoute: typeof AppCompaniesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMapRoute: AppMapRoute,
  AppNoctiRoute: AppNoctiRoute,
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
  AppCompaniesIdRoute: AppCompaniesIdRoute,
  AppCompaniesIndexRoute: AppCompaniesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForCarriersRoute: ForCarriersRoute,
  ForDriversRoute: ForDriversRoute,
  OnBoardingRoute: OnBoardingRoute,
  VerifyRoute: VerifyRoute,
  CompanyAuthRoute: CompanyAuthRoute,
  CompanyBenchmarksRoute: CompanyBenchmarksRoute,
  CompanyJobsRoute: CompanyJobsRoute,
  CompanyMapRoute: CompanyMapRoute,
  DriverAuthRoute: DriverAuthRoute,
  DriverMapRoute: DriverMapRoute,
  DriverProfileRoute: DriverProfileRoute,
  CompanyIndexRoute: CompanyIndexRoute,
  DriverIndexRoute: DriverIndexRoute,
  CompanyDriversIdRoute: CompanyDriversIdRoute,
  DriverCarriersIdRoute: DriverCarriersIdRoute,
  CompanyDriversIndexRoute: CompanyDriversIndexRoute,
  DriverCarriersIndexRoute: DriverCarriersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
